baseURL:  http://tylerferguson.me
languageCode: en-us
title: "Tyler Ferguson"
theme: "toha"
publishDir: docs

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true

# Enable Google Analytics
googleAnalytics: UA-171622243-1

# Enable Disqus forum
# optional
# disqusShortname: <your disqus short code>

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # Github Repo URL. This is used to add "Improve This Page" button
  gitRepo: https://github.com/tylerferguson